name: main

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 2 * * *'

jobs:
  testing:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.ref == 'refs/heads/main' || github.event_name != 'schedule'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npx tsc
      - name: Test all
        run: node dist/index.js ctrf-reports/ctrf-report.json --title All
        if: github.event_name != 'schedule'
      - name: Test summary
        run: node dist/index.js summary ctrf-reports/ctrf-report.json --title Summary --throw 
        if: github.event_name != 'schedule'
      - name: Test no fails or flaky
        run: node dist/index.js ctrf-reports/ctrf-report-no-fails.json
        if: github.event_name != 'schedule'
      - name: Test schedule context
        run: node dist/index.js ctrf-reports/ctrf-report.json
        if: github.event_name == 'schedule'
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ctrf-report
          path: ctrf-reports/ctrf-report.json
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: custom-artifact-name
          path: ctrf-reports/ctrf-report-no-fails.json
